# Generated by Django 4.1.7 on 2023-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
