# Generated by Django 4.1.7 on 2023-03-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_artist_artist_info_delete_artistinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('artist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='artist.artist')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('birth_place', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=50)),
            ],
        ),
    ]
