# Generated by Django 4.1.7 on 2023-03-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artistinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistInfo',
        ),
    ]
