# Generated by Django 4.1.7 on 2023-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='playlistsong',
            constraint=models.UniqueConstraint(fields=('playlist_id', 'song_id'), name='playlist_song_unique_pair'),
        ),
    ]
