# Generated by Django 4.1.7 on 2023-03-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_alter_artist_name'),
        ('album', '0003_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='artist.artist'),
        ),
    ]
