# Generated by Django 4.1.7 on 2023-03-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_playlist_songs_playlistsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song_id',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
