# Generated by Django 4.1.7 on 2023-03-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artistinfo'),
        ),
    ]
