# Generated by Django 4.1.7 on 2023-03-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_artist_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_info',
        ),
        migrations.DeleteModel(
            name='ArtistInfo',
        ),
    ]
