# Generated by Django 4.1.7 on 2023-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_delete_artistinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
