# Generated by Django 4.1.7 on 2023-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
